apiVersion: v1
kind: Service
metadata:
  name: translate-api-svc
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: translate-api-svcp
---	 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-api
  namespace: default
  labels:
    app: translate-api
spec:
  selector: 
    matchLabels:
      app: translate-api
  replicas: 1
  template:
    metadata:
      labels:
        app: translate-api
    spec:
      containers:
        - name: translate-api
          image: translate-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080